# Site description. Used in meta description
description: >-
  Objevte moderní, uměleckou a inspirativní poezii na mém blogu. Ponořte se do krásné tvorby a získejte nové uznání pro sílu slov.

# SEO keywords. Used in 'meta name="keywords"' tag.
# May be overridden by .Keywords or .Tags in front matter.
keywords:
  - Osobní poezie
  - Citová poezie
  - Agresivní myšlenky
  - Nekonvenční poezie
  - Emoční verše
  - Velice osobní básně
  - Silné emoce
  - Intenzivní výraz
  - Rebelující slova
  - Výrazný výraz
  - Vnitřní konflikt
  - Vášnivé verše
  - Emoční projev
  - Provokativní poezie
  - Kontroverzní básně
  - Silná slova
  - Výbušné myšlenky
  - Revoluční verše
  - Hluboké emocionální sdělení
  - Pohnuté slovníky
  - Výstřední básně
  - Intimní verše
  - Emoční výbuchy
  - Kontroverzní výrazy
  - Otevřená duše
  - Žhavé vášně
  - Niterné projevy
  - Nezvyklé myšlenky
  - Drsné slovníky
  - Přímá sdělení
  - Osobní výpovědi
  - Prokletá poezie
  - Zoufalé verše
  - Pálící vášeň
  - Provokativní výrazy
  - Temné emoce
  - Odvážné sdělení
  - Divoké myšlenky
  - Nebojácné verše

# A "copyright"-line to be added to RSS/Atom files.
# "&copy;" and "{year}" will be replaced by © and the current year.
copyright: "Copyright &copy; 2019-{year} Pavel Hrdina"

# Colour scheme. Options: red, orange, magenta, cyan, blue, brown
colorScheme: "brown"

# Used in site header
tagline: "Osobní blog o poezii a jejím kouzlu."

# Custom footer text on left sidebar. Use HTMl if needed.
# "&copy;" and "{year}" will be replaced by © and the current year.
footer: >-
  Toto dílo je licencováno pod licencí Creative Commons 
  Pavel Hrdina-NonCommercial-NoDerivatives 4.0 International License.

# Sections to be displayed in:
# - main page
# - RSS/Atom/Json feeds
# - search index
# - ...
mainSections:
  - posts
  - dramas
  - narratives
  - poems

# Posts date format, for example: 2006-01-02
dateFormat: ":date_long"
dateFormatToc: 2006.01.02

# Show "Read more" button in list if true
readmore: true

# RSS/Atom feed size
feedSize: 25

recentPostsSize: 5

contact:
  # Forms Backend URL, used in contacts form
  formAction: "https://submit-form.com/2XYYP3Nq"

  # Contact form email subject
  emailSubject: Odeslání kontaktního formuláře

  # Where should the user be redirected after successful form submit?
  thanksUrl: /thanks

# Site icons, relative to ./static
assets:
  # favicon.ico for legacy browsers
  favicon: "favicon.ico"

  # A single SVG icon with a light/dark version for modern browsers
  svgicon: "icon,svg"

  # 180×180 PNG image for Apple devices
  apple_touch_icon: "apple-touch-icon.png"

  # Logo image, relative to ./assets
  logo: /img/open-graph-logo.png
  disable_fingerprinting: false

seo:
  # Will be used in schema.org/Organization.
  # The site.Title  will be used if empty.
  publisher: Pavel Hrdina

  # To anonymize the IP addresses of hits sent to Google Analytics
  # set this param to true. Please note, to enable Google Analytics
  # you have to set `googleAnalytics` param in config.yaml file.
  anonymizeIp: true

social:
  # Array of Facebook Page Admin IDs for Domain Insights
  facebookAdminIds: []

  # Facebook Page ID
  facebookId: ""
# Configure search engine
# search:
# Maximum length (in words) of each text blurb. You can change this
# value if you find that 100 is too short or too long for your taste.
# maxSummaryLength: 100
# Lunr has full support for the indexing and searching of documents
# in English. If your documents are in another language, uncomment
# required languages below.
#
# For more see: https://lunrjs.com/guides/language_support.html
# languages:
# - de
# - cz
# - fr
# - it
# - pt
# - ru
